# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Hannah Rowe, PhD, CCC-SLP
email:
description: >- # this means to ignore newlines until "baseurl:"
  Hello! I am a speech scientist and certified speech-language pathologist 
  interested in speech motor control in neurologically impaired populations. 
  I completed my PhD in Rehabilitation Sciences at the MGH Institute of 
  Health Professions (advisor: Dr. Jordan Green) and am currently a 
  postdoctoral research fellow in speech neuroscience at Boston University 
  (advisor: Dr. Frank Guenther).
twitter_username: hrowe802

# change skins from this list: https://github.com/mmistakes/minimal-mistakes#skins-color-variations
minimal_mistakes_skin: dirt
search: true

# Build settings
markdown: kramdown
#remote_theme: mmistakes/minimal-mistakes
theme: minimal-mistakes-jekyll

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Hannah Rowe, PhD, CCC-SLP"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Current Postdoc at Boston University. Enthusiastic about climbing mountains, running long distances, and speech motor control."
  links:
    - label: "ResearchGate"
      icon: "fab fa-researchgate"
      url: "https://www.researchgate.net/profile/Hannah-Rowe-7/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/hrowe802/"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/hannah-rowe-35710875/"
    - label: "NIH Publication List"
      icon: "fa-solid fa-book"
      url: "https://www.ncbi.nlm.nih.gov/myncbi/hannah.rowe.2/bibliography/public/"

footer:
  links:
    - label: "ResearchGate"
      icon: "fas fa-fw fa-link"
      url: "https://www.researchgate.net/profile/Hannah-Rowe-7/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/hrowe802/"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/hannah-rowe-35710875/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
